site_name: Object Oriented Programming OOP IEC61131-3 Youtube Course by Runtimevic
docs_dir: '../../docs/en'
site_url: https://runtimevic.github.io/OOP-IEC61131-3--Curso-Youtube/
site_author: runtimevic
site_description: IEC 61131-3 PLC OOP Course

# Repository
repo_name: runtimevic/OOP-IEC61131-3--Curso-Youtube
repo_url: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
edit_uri: ""

theme:
  name: material
#  logo: images/OOP_Logo2.png
  custom_dir: overrides
  logo: images/oop_logg.webp
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  features:
#    - navigation.tabs        
  language: en
  features:
    - navigation.footer
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16    

# Plugins
plugins:
  - search:
      lang: en
  - with-pdf:
      copyright: Copyright & copy; 2023 Víctor Durán.
      cover_subtitle: Object Oriented Programming OOP IEC61131-3 PLC Youtube Course by Runtimevic.
      output_path: ../document-en.pdf
  - pdf-export:
      combined: true
               
# Customization
extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913/
    - icon: fontawesome/brands/github
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:victorduranm@hotmail.com
    - icon: fontawesome/regular/file-pdf
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube/blob/gh-pages/document-en.pdf
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/playlist?list=PLEfi_hUmmSjFpfdJ6yw3B9yj7dWHYkHmQ         
  version:
    provider: mike
  alternate:
    - name: English
      link: /OOP-IEC61131-3--Curso-Youtube/en/
      lang: en
    - name: Spanish
      link: /OOP-IEC61131-3--Curso-Youtube/es/
      lang: es
    - name: Italian
      link: /OOP-IEC61131-3--Curso-Youtube/it/
      lang: it
    - name: Portuguese
      link: /OOP-IEC61131-3--Curso-Youtube/pt/
      lang: pt
  #disqus: 'OOP IEC-61131-3 PLC'        

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: tag:yaml.org,2002:python/name:materialx.emoji.twemoji
      emoji_generator: tag:yaml.org,2002:python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true      
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde   
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: tag:yaml.org,2002:python/name:pymdownx.superfences.fence_code_format
  - meta          

nav:
    - Requeriments: requeriments.md
    - Introduction: index.md
    - Types of paradigms: Types of Paradigms.md
    - Concepts Previous:
      - Type of Data: Concepts Previous/Declaration of a Variable.md       
      - Variable types and special variables: Concepts Previous/Variable types and special variables.md
      - Access modifiers: Concepts Previous/access modifiers.md
      - Access Modifiers Table: Concepts Previous/Access Modifiers Table.md   
    - Classes and Objects:
      - Classes and Objects: Classes and Objects/Classes and Objects.md
      - Function Block: 
          - Function Block: Classes and Objects/Function Block/Function Block.md
          - Function Block Access Modifiers:  Classes and Objects/Function Block/Access modifiers Function block.md
          - Function Block Declaration variables: Classes and Objects/Function Block/Types of variables allowed in a function block.md
          - Constructor and Destructor: Classes and Objects/Function Block/Constructor and Destructor.md          
      - Object Method:
          - Method: Classes and Objects/Object Method/Method.md
          - Method access modifiers: Classes and Objects/Object Method/Access specifiers for methods.md
          - Method Declaration of variables: Classes and Objects/Object Method/Types of variables allowed in a method.md
          - Method return variable types: Classes and Objects/Object Method/Types of return variables.md      
      - Object Property: Classes and Objects/Properties.md
      - Inheritance:
          - Inheritance Function Block: Classes and Objects/Inheritance/Inheritance Function Block.md
          - Inheritance Structure: Classes and Objects/Inheritance/Inheritance Structure.md
          - Inheritance Interface: Classes and Objects/Inheritance/Inheritance Interface.md
      - THIS pointer: Classes and Objects/THIS pointer.md
      - SUPER pointer: Classes and Objects/SUPER pointer.md    
      - Interface: Classes and Objects/interface.md
      - pointer and reference: Classes and Objects/pointer and reference.md
      - Keyword Abstract: Classes and Objects/Keyword_Abstract.md
      - Abstract FB vs Interface: Classes and Objects/Abstract FB in front of interface.md
      - Fluent Interface: Classes and Objects/Fluid Interface.md
      - Interface vs Inheritance: Classes and Objects/Interface vs Inheritance.md
      - Further operators: Classes and Objects/Other Operators.md
    - ExST:
      - Extended Structured Text: Extended_Structured_Text.md   
    - OOP Principles: 
      - 4 Pillars: Principles/_Principles OOP.md
      - Abstraction: Principles/abstraction.md
      - Encapsulation: Principles/encapsulation.md
      - Inheritance: Principles/inheritance.md
      - Polymorphism: Principles/polymorphism.md    
    - SOLID: 
      - SOLID: solid/_SOLID.md
      - SRP - Single Responsibility Principle: solid/Single Responsibility Principle.md
      - OCP - Open/Closed Principle: solid/Open_Closed Principle.md
      - LSP - Liskov Substitution Principle: solid/Liskov Substitution Principle.md
      - ISP - Interface Segregation Principle: solid/Interface Segregation Principle.md
      - DIP - Dependency Inversion Principle: solid/Dependency Inversion Principle.md
    - UML: 
      - UML: UML/UML.md
      - Class UML: UML/Class UML.md
      - Relations: UML/relations.md
      - StateChart UML: UML/Statechart UML.md
    - Types of Design for PLC programming: Types of Design for PLC programming.md
    - Design patterns:
      - Design patterns: Design Patterns/_Design Patterns.md
      - Strategy Pattern: Design Patterns/Strategy pattern.md
      - The Abstract Factory Pattern: Design Patterns/The Abstract Factory Pattern.md
      - The Visitor Design Pattern: Design Patterns/The Visitor Design Pattern.md
    - Libraries : Libraries.md
    - Links OOP: links.md
    - TDD:
      - TDD - Test Drive Development: TDD/Test Driven Development.md
      - Units Test: TDD/Unit Test.md