site_name: Programação Orientada a Objeto OOP IEC61131-3 Curso Youtube por Runtimevic
docs_dir: '../../docs/pt'
site_url: https://runtimevic.github.io/OOP-IEC61131-3--Curso-Youtube/pt/
site_author: Kauê Koschitz Roratto
site_description: Curso OOP 61131-3 PLC

# Repository
repo_name: runtimevic/OOP-IEC61131-3--Curso-Youtube
repo_url: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
edit_uri: ""

theme:
  name: material
#  logo: imagenes/OOP_Logo2.png
  custom_dir: overrides
  logo: imagens/oop_logg.webp
  palette:
     # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
#  features:
#    - navigation.tabs        
  language: pt
  features:
    - navigation.footer
        
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16    

# Plugins
plugins:
  - search:
      lang: pt
  - with-pdf:
      copyright: Copyright &copy; 2023 Víctor Durán.
      cover_subtitle: Programación Orientada a Objetos OOP IEC61131-3 PLC Curso Youtube by Runtimevic.
      output_path: ../document-pt.pdf
  - pdf-export:
      combined: true                  

# Customization
extra:
  analytics:
    provider: google
    property: G-42EY64EE3Z
  consent:
    title: Cookie consent
    description: >- 
      Utilizamos cookies para reconocer sus visitas repetidas y preferencias, así como
      como para medir la eficacia de nuestra documentación y si los usuarios
      encuentran lo que están buscando. Con su consentimiento, nos está ayudando a
      mejorar nuestra documentación.
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.    
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/v%C3%ADctor-dur%C3%A1n-mu%C3%B1oz-2879a913/
    - icon: fontawesome/brands/github
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube
    - icon: fontawesome/solid/paper-plane
      link: mailto:victorduranm@hotmail.com
    - icon: fontawesome/regular/file-pdf
      link: https://github.com/runtimevic/OOP-IEC61131-3--Curso-Youtube/blob/gh-pages/document-pt.pdf
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/playlist?list=PLEfi_hUmmSjFpfdJ6yw3B9yj7dWHYkHmQ       
  version:
    provider: mike
  alternate:
    - name: Inglês
      link: /OOP-IEC61131-3--Curso-Youtube/en/
      lang: en
    - name: Espanhol
      link: /OOP-IEC61131-3--Curso-Youtube/es/
      lang: es
    - name: Italiano
      link: /OOP-IEC61131-3--Curso-Youtube/it/
      lang: it
    - name: Português
      link: /OOP-IEC61131-3--Curso-Youtube/pt/
      lang: pt             

markdown_extensions:
  - attr_list
  - md_in_html  
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true      
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde   
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - meta     
  
nav:
    - Requisitos: requisitos.md
    - Introdução: index.md
    - Tipos de paradigmas: tipos de paradigmas.md
    - Conceitos anteriores:
       - Tipos de Dados: Conceitos anteriores/Tipos de datos.md       
       - Tipos de variáveis ​​e variáveis ​​especiais: Conceitos anteriores/Variable types and special variables.md
       - Modificadores de acesso: Conceitos anteriores/modificadores de acceso.md
       - Tabela de Modificadores de acesso: Conceitos anteriores/Tabla de Modificadores de acceso.md      
    - Classes e Objetos:
       - Classes e Objetos: Clases e Objetos/clases y objetos.md
       - Bloco de funções: 
          - Bloco de funções: Clases e Objetos/Function Block.md
          - Bloco de funções Modificadores de acesso:  Clases e Objetos/Function Block Modificadores de acceso.md
          - Bloco de funções Declaração de variáveis: Clases e Objetos/Function Block Declaracion de variables.md
          - Construtor e Destruidor: Clases e Objetos/Constructor y Destructor.md          
       - Objeto Método: 
          - Método: Clases e Objetos/metodo.md
          - Método Modificadores de acesso: Clases e Objetos/Metodo Modificadores de acceso.md
          - Método Declaração de variáveis: Clases e Objetos/Metodo Declaracion de variables.md
          - Método tipos de variável de retorno: Clases e Objetos/Metodo Tipos de variables de retorno.md
       - Objeto Propiedade: Clases e Objetos/propiedad.md
       - Herança:
          - Herança Bloco de funções: Clases e Objetos/Herencia/Herencia Bloque de Funcion.md
          - Herança Estrutura: Clases e Objetos/Herencia/Herencia Estructura.md
          - Herança Interface: Clases e Objetos/Herencia/Herencia Interface.md
       - THIS ponteiro: Clases e Objetos/THIS pointer.md
       - SUPER ponteiro: Clases e Objetos/SUPER pointer.md
       - Interface: Clases e Objetos/interface.md
       - ponteiro e referência: Clases e Objetos/pointer and reference.md
       - Palavra chave Abstrato: Clases e Objetos/Keyword_Abstract.md
       - FB Abstrato vs Interface: Clases e Objetos/FB abstracto frente a interfaz.md
       - Interface fluido: Clases e Objetos/Interfaz fluida.md
       - Interface vs Herança: Clases e Objetos/Interface vs Herencia.md
       - Outros Operadores: Clases e Objetos/Otros Operadores.md
    - ExST:
       - Texto Estruturado Estendido: Extended_Structured_Text.md
    - Começo OOP: 
       - 4 Pilares: começo/_principios OOP.md
       - Abstração: começo/abstraccion.md
       - Encapsulamento: começo/encapsulamiento.md
       - Herança: começo/herencia.md
       - Polimorfismo: começo/polimorfismo.md    
    - SOLID: 
       - SOLID: solid/_SOLID.md
       - SRP - Princípio da Responsabilidade Individual: solid/Principio de Responsabilidad Unica.md
       - OCP - Princípio Aberto/Fechado: solid/Principio de Abierto_Cerrado.md
       - LSP - Princípio da Substituição de Liskov: solid/Principio de Sustitucion de Liskov.md
       - ISP - Princípio de Segregação de Interface: solid/Principio de Segregacion de Interfaz.md
       - DIP - Princípio de Inversão de Dependência: solid/Principio de Inversion de Dependencia.md
    - UML: 
       - UML: UML/UML.md
       - Class UML: UML/Class UML.md
       - Relações: UML/relaciones.md
       - StateChart UML: UML/Statechart UML.md
    - Tipos de Design para programação de PLC: Tipos de Design para programação de PLC.md
    - Padrões de Design:
       - Padrões de Design : Padrões de Design/_Patrones de Diseño.md
       - Padrões de Design Criacional:
          - Padrão Método de fábrica: Padrões de Design/Factory Method Design Pattern.md
          - Padrão Fábrica Abstrata: Padrões de Design/The Abstract Factory Pattern.md
       - Padrões de Design Estrutural:
          - Padrão Decorador: Padrões de Design/Decorator Design Pattern.md
       - Padrões de Design de Comportamento:
          - Padrão de Estratégia: Padrões de Design/Strategy pattern.md
          - Padrão Observador: Padrões de Design/Observer Design Pattern.md
          - Padrão Visitante: Padrões de Design/The Visitor Design Pattern.md
    - Livrarias : Livrarias.md
    - Links OOP: links.md
    - TDD:
       - TDD - Desenvolvimento Orientado a Testes: TDD/Test Driven Development.md
       - Testes de Unidade: TDD/Unit Test.md
 